### ISSUE TITLE
navigation2 mapserver segfault/interrupted

### ISSUE THREAD

**Issue by emersonknapp** [mikaelarguedas/tb3_demo#17]
# Issue
when running the nav2 mapserver, it either prints a message "interrupted" or segfaults

Setup
```
docker build . -t rosswg/turtlebot3_demo
rocker --x11 rosswg/turtlebot3_demo "byobu -f configs/unsecure.conf attach"
```

Move to "mapping" window
```
root@3dddc873fd3d:/opt# ros2 run nav2_map_server map_saver -f maps/map
[INFO] [map_saver]: Waiting for the map
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
root@3dddc873fd3d:/opt# ros2 run nav2_map_server map_saver -f maps/map
[INFO] [map_saver]: Waiting for the map
Map saver failed: interrupted
```

## Expected result
Map is served so that I can send goal poase via RViz

## Actual result
"Map saver failed: interrupted" or "Segmentation Fault...", not strictly alternating, seems random which one

## System Information
```
5:43:17 ➜  ~ rocker --version                                                                                                                                                         0s 
Plugins found: ['dev_helpers', 'env', 'git', 'home', 'nvidia', 'pulse', 'ssh', 'user', 'x11']
rocker 0.1.8
5:43:19 ➜  ~ docker --version                                                                                                                                                         0s 
Docker version 18.09.5, build e8ff056
```

**Comment by ruffsl** [comment]
Are you attempting to run the map server to save the map when the navigation launch file is running? I think the navigation launch file is already running a map server to publish the static map copied into the docker image; perhaps the duplicate nodes are colliding over namespaces. If you halt the navigation launch file, then start cartographer and move around, then you can use the map server save command to save the map you just explored.

I would be kind of cool to have navigation and cartographer running simultaneously, e.g. clicking on an unexplored occupancy, and having the navigation stack steadily plan towards the frontier. But that might be a little out of scope for the demo's purpose, and adding cartographer to the startup might add to the overhead.

**Comment by emersonknapp** [comment]
I think maybe the setup is just unclear. It seems like we've set up a nice sandbox to play in, but  more directed "navigation2 demo", "cartographer demo" byobu setups might relieve some of the issue here

i think in my case i'm not able to see the map in rviz because of an rviz bug, and because of that thought i needed to start a map server, saw a command queued up called mapserver, and tried to run it

**Comment by emersonknapp** [comment]
i dind't read `map_saver` - i read it as `map_server` haha
